name: labels
on:
  push:
    branches: [main]
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: crazy-max/ghaction-github-labeler@v3
        with:
          yaml-file: .github/labels.yml
